version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-image
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    secrets:
      - user_ssh_key
    networks:
      - app-network

  # db:
  #   image: mysql:5.7
  #   container_name: laravel-db
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./mysql/my.cnf:/etc/mysql/my.cnf
  #     - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  #   networks:
  #     - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  redis:
    image: redis:4.0
    container_name: laravel-redis
    ports:
      - "6382:6379"
    networks:
      - app-network

  node:
    # image: node:12-alpine
    image: jwigley/alpine-node-git-yarn:node-12
    container_name: laravel-node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

networks:
  app-network:
    driver: bridge

secrets:
  user_ssh_key:
    file: ~/.ssh/id_ed25519